/** Original scene IDs from bank 6:$471C (10-byte records). FINI is the ending. */
export const levels = [
  { id: 0, label: "01 · Museum · opening" },
  { id: 1, label: "02 · Museum · room 1" },
  { id: 2, label: "03 · Museum · room 2" },
  { id: 3, label: "04 · Museum · room 3" },
  { id: 4, label: "05 · Museum · room 4" },
  { id: 5, label: "06 · Warehouse" },
  { id: 6, label: "07 · Mansion · room 1" },
  { id: 7, label: "08 · Mansion · room 2" },
  { id: 8, label: "09 · Mansion · room 3" },
  { id: 9, label: "10 · Mansion · room 4" },
  { id: 10, label: "11 · Grounds" },
  { id: 11, label: "12 · Car chase" },
  { id: 12, label: "13 · Port · area 1" },
  { id: 13, label: "14 · Port · area 2" },
  { id: 14, label: "15 · Ship · area 1" },
  { id: 15, label: "16 · Ship · area 2" },
  { id: 16, label: "17 · Ship · cabin" },
  { id: 17, label: "18 · Town · area 1" },
  { id: 18, label: "19 · Town · area 2" },
  { id: 19, label: "20 · Town · area 3" },
  { id: 20, label: "21 · Rescue" },
  { id: 21, label: "22 · Condor" },
  { id: 22, label: "23 · Snow" },
  { id: 23, label: "24 · River" },
  { id: 24, label: "25 · Waterfall" },
  { id: 25, label: "26 · Caves · area 1" },
  { id: 26, label: "27 · Caves · area 2" },
  { id: 27, label: "28 · Caves · area 3" },
  { id: 28, label: "29 · Caves · area 4" },
  { id: 29, label: "30 · Eclipse puzzle" },
  { id: 30, label: "31 · Temple" },
];
